version: '3.2'

services:

  logger:
    image: egeldenhuys/dalla-stats-logger:arm32v7
    restart: always
    networks:
      - dalla_stats_network
    secrets:
      - dalla_logger_config
    deploy:
      placement:
        constraints:
          - node.hostname == sherlock

  ui:
    image: egeldenhuys/dalla-stats-ui:arm32v7
    restart: always
    networks:
      - dalla_stats_network
    ports:
      - "80:80"
    deploy:
      placement:
        constraints:
          - node.hostname == sherlock

  db:
    image: yobasystems/alpine-mariadb:arm32v7
    restart: always
    environment:
      MYSQL_USER: dalla
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dalla_stats
    volumes:
      - "dalla_stats_data:/var/lib/mysql"
    networks:
      - dalla_stats_network
    deploy:
      placement:
        constraints:
          - node.hostname == sherlock

volumes:
  dalla_stats_data:
    external: true

networks:
  dalla_stats_network:

secrets:
  dalla_logger_config:
    file: config.local.ini
