version: '3.2'

services:

  logger:
    image: egeldenhuys/dalla-stats-logger:latest
    networks:
      - dalla_stats_network
    secrets:
      - dalla_logger_config
    deploy:
      placement:
        constraints:
          - node.hostname == leonidas

  ui:
    image: egeldenhuys/dalla-stats-ui:latest
    restart: always
    networks:
      - dalla_stats_network
    ports:
      - "9000:80"
    deploy:
      placement:
        constraints:
          - node.hostname == leonidas

  db:
    image: egeldenhuys/dalla-stats-db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - "dalla_stats_data:/var/lib/mysql"
    networks:
      - dalla_stats_network
    secrets:
      - mysql_root_password
    deploy:
      placement:
        constraints:
          - node.hostname == leonidas

volumes:
  dalla_stats_data:
    external: true

networks:
  dalla_stats_network:

secrets:
  mysql_root_password:
    file: mysql_root_password.txt
  dalla_logger_config:
    file: config.local.ini